### ISSUE TITLE
Is this official cookbook for graphite

### ISSUE THREAD

**Issue by praste** [opscode-cookbooks/oc-graphite#3]
Is this official graphite cookbook or https://github.com/hw-cookbooks/graphite is ?

**Comment by paulmooring** [comment]
This cookbook is used internally at Chef.  While it's available to use, it's not intended to be a "supported community cookbook" and as such is not on supermarket.chef.io.  I can't speak for heavywater, but the other cookbook you linked does appear to target general/public usage.  However, I don't think there is such a thing as an "official graphite cookbook" so I would recommend using whatever cookbook supports your use case and you're comfortable running.
